import { expect } from "bun:test"
import fs from "node:fs"
import path from "node:path"

const modelsSnapshotPrefix = "// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = "

export function writeCurrentModelsFixture(root: string, dir: string) {
  const modelsSnapshot = path.join(root, "src", "provider", "models-snapshot.js")
  const snapshotSource = fs.readFileSync(modelsSnapshot, "utf8")
  expect(snapshotSource.startsWith(modelsSnapshotPrefix)).toBe(true)

  const fixture = path.join(dir, "api.json")
  fs.writeFileSync(fixture, snapshotSource.slice(modelsSnapshotPrefix.length).trim())
  return { fixture, modelsSnapshot, snapshotSource }
}

export function expectModelsSnapshotUnchanged(input: { modelsSnapshot: string; snapshotSource: string }) {
  expect(fs.readFileSync(input.modelsSnapshot, "utf8")).toBe(input.snapshotSource)
}
